### ISSUE TITLE
how to use this extension? ti seems doesn't work

### ISSUE THREAD

**Issue by easyeda2021** [corvis/easyeda-bulkops#1]
Hi
thanks for your extension, but it seems doesn't work when copy params and then paste

**Comment by corvis** [comment]
Just double checked and it seems to work as intended. Please make sure you use compiled version from [Releases page](https://github.com/corvis/easyeda-bulkops/releases/latest), not just a source code. I also updated readme with usage and installation instructions.

Also the purpose of the plugin to replace meta info of the extension. E.g. you have some particular capacitor from LCSC (having specific part number and all other details) and you want to replace it with another part of the same footprint but probably different  characteristics. Then you 

1. add a new part on the canvas somewhere.
2. select the new part
3. click BulkOps/Copy Params in the main menu. The warning dialog explaining how this functionality works will appear
4. select all parts you would like to replace
5. click BulkOps/Paste Params. The components should be updated.

Please let me know if this helps or provide some more details if it's still doesn't work.

**Comment by AmunRa7** [comment]
to me it doesn't appear at all! would very much love to have this i don't know why this isn't an option that's already there.
![Screenshot 2023-05-13 225111](https://github.com/corvis/easyeda-bulkops/assets/20719653/2dd03457-e0f0-4db7-bf5c-cd94389acb6c)

**Comment by easyeda2021** [comment]
> to me it doesn't appear at all! would very much love to have this i don't know why this isn't an option that's already there. ![Screenshot 2023-05-13 225111](https://private-user-images.githubusercontent.com/20719653/238154205-2dd03457-e0f0-4db7-bf5c-cd94389acb6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjA5NTQsIm5iZiI6MTcwNDg2MDY1NCwicGF0aCI6Ii8yMDcxOTY1My8yMzgxNTQyMDUtMmRkMDM0NTctZTBmMC00ZGI3LWJmNWMtY2Q5NDM4OWFjYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA0MjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2E4NmRiNGUzZDNmYjFmMjIyYzIyNGQyNzEyMDc1NjZiZWJjYjVkMTA5ZDJlOTI5MWI5YjJlMTQzMmNiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.43EGjsGB3V6h0sEKho-XhbbOiGxOFExt1GWdmcqXQ-g)

hi， it works as Corvis said, and it only works at schematic
